# Stage 1: Build the JAR
FROM maven:3.9.5-eclipse-temurin-17 AS builder
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Stage 2: Run the JAR
FROM openjdk:17-jdk-slim
RUN apt-get update && apt-get install -y ca-certificates && apt-get clean
RUN apt-get install -y openssl
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
EXPOSE 8088
EXPOSE 587
ENTRYPOINT ["java", "-jar", "app.jar"]
