server:
  port: 8081

spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8083/
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: http://localhost:8088
          predicates:
            - Path=/user/**

        - id: Code-Execution-Handler
          uri: http://localhost:9090
          predicates:
            - Path=/code/**
          filters:
            - name: AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
